### ISSUE TITLE
Support for more services -- SageMaker Notebook and Gateway Endpoints (S3/Dynamo)

### ISSUE THREAD

**Issue by elementalvoid** [plus3it/terraform-aws-tardigrade-vpc-endpoints#49]
Hi there! First, let me say thank you for putting this module out here for others. It gave us a great start. But we did find a couple of things that we wanted to adjust for our project and we'd love to submit a PR if you're open to it.

First, I found that the module doesn't support SageMaker Notebook because this service uses a "non-standard" fully qualified service name. It also doesn't seem to have a common name; it can _only_ be referenced by the full name (ex: `aws.sagemaker.us-east-1.notebook`).

Second, I wanted to be able to use the module for both Interface and Gateway type Endpoints.

Lastly, I wanted to use `for_each` on the endpoints to avoid list sorting issues as we add/remove endpoints.

I forked the repository and [have already implemented these features](https://github.com/Ibotta/terraform-aws-tardigrade-vpc-endpoints/pull/1/files). For my company's internal purposes we already have a PR on our fork. I would be happy to submit one here!

**Comment by elementalvoid** [comment]
Of those three the one with the biggest user impact is the `for_each` change. The others could be implemented in a backward-compatible manner.

**Comment by elementalvoid** [comment]
Alright. I'll get one created soon!

**Comment by lorengordon** [comment]
Thanks @elementalvoid! Could you also create a test config in `tests/` to exercise the sagemaker endpoint and the Gateway-type endpoint? You can either extend an existing config or write a new one...
